Update Readme.md
htmlacademy-htmlcss/1972445-sedona-1 pull request #1
Opened 2023-12-07 07:02 UTC by Cognosceteipsum1989

Добавляю наставника

2023-12-07 07:37 UTC, Cognosceteipsum1989 commented
изменения

2023-12-08 02:31 UTC, Cognosceteipsum1989 commented
изменения: добавляю наставника

2023-12-08 06:12 UTC, jumile requested changes

2023-12-08 06:12 UTC, jumile commented on Readme.md
> +* Наставник: `Ирина Антипина`.
Еще нужна ссылка на профиль наставника.

2023-12-10 06:42 UTC, Cognosceteipsum1989 commented
Доброго дня! ссылка добавлена!

2023-12-10 17:36 UTC, jumile approved these changes
Отлично!

2023-12-10 17:36 UTC, merged