Доработка по разделу графика
htmlacademy-htmlcss/1972445-sedona-1 pull request #4
Opened 2024-01-09 10:17 UTC by Cognosceteipsum1989

2024-01-23 13:04 UTC, Cognosceteipsum1989 commented
раздел 4

2024-01-24 14:33 UTC, jumile requested changes

2024-01-24 14:33 UTC, jumile commented on catalog.html
> +  <div class="sorting-container">
Лишняя обертка

2024-01-24 14:33 UTC, jumile commented on catalog.html
> +</div>
Здесь обертки не хватает для 3 кнопок.

2024-01-24 14:33 UTC, jumile commented on catalog.html
> +  <a class="button button-hotels button-cards active" href="#" >
Не много ли здесь классов?

2024-01-24 14:33 UTC, jumile commented on catalog.html
>          <span class="visually-hidden"></span>
Добавьте про 4 звезды в span.

2024-01-24 14:33 UTC, jumile commented on catalog.html
> +      <a class="pagination-link" href="">10</a>
href="#"

2024-01-24 14:33 UTC, jumile commented on catalog.html
>        <input type="email" name="destribution-form" placeholder="Ваш e-mail" id="em" required></label>
Label не должен быть пустым.
label.visually-hidden   Ваш e-mail   /label
input ...

2024-01-24 14:33 UTC, jumile commented on catalog.html
> +          <img src="images/icons-social/social-vk.svg" alt="Вконтакте" width="24" height="14">
Иконка - не контент.

2024-01-24 14:33 UTC, jumile commented on catalog.html
>      </ul>
В номере телефона скобки не нужны.

2024-01-24 14:33 UTC, jumile commented on index.html
> +          <div class="blog-advantages blog-advantages-1">
Здесь нельзя div

2024-01-24 14:33 UTC, jumile commented on index.html
> +            <div class="blog-advantages blog-advantages-1">
div нельзя здесь.

2024-01-24 14:33 UTC, jumile commented on styles/styles.css
> +  font-family: 'PT Sans';
Кавычки двойные.

2024-01-24 14:33 UTC, jumile commented on styles/styles.css
> +  src: url("../fonts/pt-sans-regular.woff2") format("woff2");
Другой файл нужен.

2024-01-24 14:33 UTC, jumile commented on styles/styles.css
> +  font-family: 'PT Sans';
Разве у нас есть курсив?

2024-01-24 14:33 UTC, jumile commented on styles/styles.css
> +  background-image: url('../images/icons-header/search.svg');
кавычки двойные

2024-01-24 14:33 UTC, jumile commented on styles/styles.css
> +  background-image: url('../images/icons-header/like.svg');
кавычки двойные

2024-01-24 14:33 UTC, jumile commented on styles/styles.css
> +  background: cyan url("../images/index-hero/index-background.jpg") no-repeat;
Цвет надо писать в HEX

2024-01-24 14:33 UTC, jumile commented on styles/styles.css
> +  background-color: #82B3D3;
Буквы в кодах цветов маленькие.

2024-01-24 14:33 UTC, jumile commented on styles/styles.css
> +  background-image: url('../images/catalog-hero/home-breadcrumbs.svg');
кавычки двойные

2024-01-24 14:33 UTC, jumile commented on styles/styles.css
> +.button-form-last {
button-form-last

2024-01-24 14:33 UTC, jumile commented on styles/styles.css
> +  background: transparent no-repeat;
no-repeat не нужен

2024-01-26 14:41 UTC, merged